# Generated by Django 5.0.3 on 2024-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_bookingdetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='booking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
