# Generated by Django 5.0.3 on 2024-05-25 08:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_booking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_event_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
